### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by RomuloSouza**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by filipetoyoshima** [comment]
Everything looks okay, except by the fact that now the token is set at URL. Is this right? I remember that, before, we used environment variables to access the data.

Anyway, what I see is okay, but I would prefer someone who knows more about the API to check this.
@cjjcastro @Hiroshi18

**Comment by cjjcastro** [comment]
As the user token needs to be entered in the request it can no longer be passed as environment variable

**Comment by cjjcastro** [comment]
But I agree that going through the url is not the best solution. It would be more appropriate to pass by header. We can open a new issue to solve this.

**Review by cjjcastro — APPROVED** [review]
In my opinion this acceptable

**Pull request merged**
